### DISCUSSION TITLE
what's the meaning of  `filter - app`?

### DISCUSSION THREAD

**Discussion by liaodalin19903** [saltyshiomix/nextron#359] [Q&A]
In the [nextron#build-configuration](https://github.com/saltyshiomix/nextron#build-configuration),

what's the meaning of  `filter - app`?:
```
files:
  - from: .
    filter:
      - package.json
      - app
```

in the [document](https://www.electron.build/configuration/configuration), I didn't find the configuration.
