### DISCUSSION TITLE
Build a single exe with nextron

### DISCUSSION THREAD

**Discussion by lucabmn** [saltyshiomix/nextron#397] [General]
Hi, is it possible to build a single runnable exe with nextron?
Something like "electron-builder --win portable"

**Comment by Psycokwet** [comment]
I'm not sure I understand your question, when you build on windows, you get a single .exe file inside the build folder, you can just use that as a standalone

**Comment by saltyshiomix** [comment]
@lucabmn 
This is not a nextron issue.
I think it is impossible for us to build a single runnable exe by using Electron.

If we want to do that, we must develop the app in Rust or something else that supports portable executable app.

**Reply by lucabmn** [reply]
With electron its possible with the electron-builder package, but that one isnt working with nextron

**Reply by saltyshiomix** [reply]
@lucabmn 
Oh, sorry for inconvenience.

Currently nextron does not support full options for electron-builder.
So we need to update nextron command, which I will handle next release 🙇 

FYI:

- https://github.com/saltyshiomix/nextron/issues/398
  - v8.10.0
    - Improve nextron command options

**Reply by saltyshiomix** [reply]
@lucabmn 

I found the option `portable` can be met in `electron-builder.yml`: https://www.electron.build/configuration/configuration.html

And there are no CLI option `portable`, so please check it out the above :)

**Reply by saltyshiomix** [reply]
A working sample is here:

```yml
appId: com.example.nextron
productName: My Nextron App
copyright: Copyright © 2018 Yoshihide Shiono
directories:
  output: dist
  buildResources: resources
files:
  - from: .
    filter:
      - package.json
      - app
publish: null

win:
  target: portable # <= add this
```
