### ISSUE TITLE
extraResources

### ISSUE THREAD

**Issue by paragbaxi** [saltyshiomix/nextron#107]
https://stackoverflow.com/questions/46022443/electron-how-to-add-external-files

I'm trying to add extraResources for a tray icon to work in production (`yarn build`). I have to modify the build command to do this, but the build command just points to `nextron build`. 

How do I modify the `nextron build` command to include extraResources?

**Comment by paragbaxi** [comment]
So I was able to figure it out. Nextron passes the `electron-builder.yml` file to electron-builder.

here's a relevant subset of that yml file that enables extraResources:
```
directories:
  output: dist
  buildResources: resources
extraResources:
  - from: './src/extraResources'
    to: 'extraResources'
    filter:
      - '**/*'
files:
```

**Comment by saltyshiomix** [comment]
@paragbaxi 

Thanks to your big efforts to clarify the issue and kindness :)

**Comment by Jaikant** [comment]
I added this to my project and the app grew so big it exhausted all the space on the drive! 
While, the same extraResources on an electron app without nextron worked fine. I suspect nextron is doing some optimisations which is causing the files in extraResources enter an endless loop. Here is how my file looks ..

```
files:
  - from: .
    filter:
      - package.json
      - app
extraResources:
  - from: '../env'
  - to: env
  - filter:
      - '**/*'
      - '!*.pyc'
      - '!conda-meta${/*}'
asar: false
publish: null

```

**Comment by Jaikant** [comment]
> I added this to my project and the app grew so big it exhausted all the space on the drive!
> While, the same extraResources on an electron app without nextron worked fine. I suspect nextron is doing some optimisations which is causing the files in extraResources enter an endless loop. Here is how my file looks ..
> 
> ```
> files:
>   - from: .
>     filter:
>       - package.json
>       - app
> extraResources:
>   - from: '../env'
>   - to: env
>   - filter:
>       - '**/*'
>       - '!*.pyc'
>       - '!conda-meta${/*}'
> asar: false
> publish: null
> ```

Ok! There was an issue with my yml format. The extra '-' in the extraResources. Debugging took a few hours! Hope this helps someone. The config below works.

```
extraResources:
  - from: '../env'
    to: env
    filter:
      - '**/*'
      - '!*.pyc'
      - '!conda-meta${/*}'

```
