### ISSUE TITLE
Adding dll in build

### ISSUE THREAD

**Issue by Psycokwet** [saltyshiomix/nextron#120]
Hello !
I need to pack dll with my build, it's not clear to me how I can do that with nextron ?
I have been using the IPC-communication example, and use a library wrapper to use dll into node.
It works perfectly on the dev side until now.
Outside from the dll issue, the reste of the code seem to run fine on the build side too.

**Comment by saltyshiomix** [comment]
Hi @Psycokwet , thank you for your question :)

Please let me know that the DLLs are the external files?

If so, in production, we should include that DLLs in the `app` directory via `electron-builder.yml`:

```yml
appId: com.example.nextron
productName: My Nextron App
copyright: Copyright © 2018 Yoshihide Shiono
directories:
  output: dist
  buildResources: resources
files:
  - from: .
    filter:
      - package.json
      - app
      - another/file <---- here
publish: null
```

If the DLLs are included in the node_modules, I think your code works fine both of dev and prod environment :)

**Comment by Psycokwet** [comment]
Thank you ! No, the DLL are not part of node_modules, since there is dll for windows, other for macos, I think it may be best to include them myself in the build (I've made the npm package, it's an updated version of another which wasn't maintained anymore, and I followed the original idea to not put them into the package)

Thank you ! I found informations about this, but couldn't find the exact syntaxe to use !

Do you know if there is a way to specify which dll to put in the executable depending on the target operating system? Again, I am mainly not sure of the syntax but I believe there is a way !

Do you think it would be better to include the dlls directly? 
Since they are not mine anyway, and this is a lib that can be priced depending the usage, I'm don't think I should do it anyway. :o

**Comment by Psycokwet** [comment]
Update : I tried what you told me, but didn't get the dll into the packaged build, or maybe I didn't look at the right place?
Here is my builder file: 
appId: com.example.nextron
productName: My Nextron App
copyright: Copyright © 2018 Yoshihide Shiono
directories:
  output: dist
  buildResources: resources
files:
  - from: .
    filter:
      - package.json
      - app
      - lib\bass32bit\bass.dll
publish: null


The lib folder is a the root of my project !

**Comment by saltyshiomix** [comment]
Ok, I got it.

Something like this might work:

```
files:
  - from: .
    filter:
      - package.json
      - app
  - from: lib/bass32bit/bass.dll
    to: app/lib/bass32bit/bass.dll
```

And then, inside `asar` file tree is like this:

```
app/
  lib/bass32bit/bass.dll
```

Finally, be careful to find the path to the dll:

```js
// won't work
path.join(process.cwd(), 'lib/bass32bit/bass.dll');

// would work
import { app } from 'electron';
path.join(app.getAppPath(), 'lib/bass32bit/bass.dll');
```

**Comment by saltyshiomix** [comment]
@Psycokwet 

> Do you know if there is a way to specify which dll to put in the executable depending on the target operating system? Again, I am mainly not sure of the syntax but I believe there is a way !

See https://nodejs.org/api/os.html#os_os_platform

**Comment by saltyshiomix** [comment]
> Do you think it would be better to include the dlls directly? Since they are not mine anyway, and this is a lib that can be priced depending the usage, I don't think I should do it anyway. :o

I think it would be ok to include the DLLs directly within the lisence of that lib :)

**Comment by Psycokwet** [comment]
> Ok, I got it.
> 
> Something like this might work:
> 
> ```
> files:
>   - from: .
>     filter:
>       - package.json
>       - app
>   - from: lib/bass32bit/bass.dll
>     to: app/lib/bass32bit/bass.dll
> ```
> 
> And then, inside `asar` file tree is like this:
> 
> ```
> app/
>   lib/bass32bit/bass.dll
> ```
> 
> Finally, be careful to find the path to the dll:
> 
> ```js
> // won't work
> path.join(process.cwd(), 'lib/bass32bit/bass.dll');
> 
> // would work
> import { app } from 'electron';
> path.join(app.getAppPath(), 'lib/bass32bit/bass.dll');
> ```

I tried this, and then tried to check with fs if the file exist, in dev environnement it does, but in build, it doesn't, maybe asar archives must be accessed by others means?





> @Psycokwet
> 
> > Do you know if there is a way to specify which dll to put in the executable depending on the target operating system? Again, I am mainly not sure of the syntax but I believe there is a way !
> 
> See https://nodejs.org/api/os.html#os_os_platform

I looked at this, and wonder what you mean? I already have some code to choose the right folder on my app, depending on the os, but I saw https://www.electron.build/configuration/configuration in this that it may be possible to get different configuration to build depending on the os? I'm sorry, I hope I am not asking too much ^^' I'm a bit confused with how configuration works.

Also, i'm confused as why when building an executable, I kind of get two ?  One "my nextron app setup" which install the software on my computer, and in win-unpacked, still in the dist folder, there is another one which is a bare executable. Does the the first one need the win-unpacked folder to install on the computer? Or does the setup one contain everything it need to install into the computer?



> > Do you think it would be better to include the dlls directly? Since they are not mine anyway, and this is a lib that can be priced depending the usage, I don't think I should do it anyway. :o
> 
> I think it would be ok to include the DLLs directly within the lisence of that lib :)

Ok, I will see about that, thank you. :) 
In the meantime, I think this issues is still relevant, we may need to includes other files into the executable by some means (and also, I want to check first if the dll owner is ok with that ahah)

**Comment by Psycokwet** [comment]
Anyway, thank you for your help. You are doing a great work ! I hope I will be able to offer a valuable contribution to your project (nextron) someday !

**Comment by Psycokwet** [comment]
Arf, my mistake... I does get into the asar archive, but, it does not get into the installation folder :(

I tried this too 
```yaml
appId: com.example.nextron
productName: Vestalive
copyright: Copyright © 2018 Yoshihide Shiono
directories:
  output: dist
  buildResources: resources
files:
  - from: .
    filter:
      - package.json
      - app
  - from: resources
    filter:
      - icon-microoff.png
      - microon.png
    to: app/test
publish: null
```
